language: generic
services:
  - docker

before_install:
  - docker build -t akshitsehgal297/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true akshitsehgal297/react-test npm run test

after_success:
  - docker build -t akshitsehgal297/multi-client ./client
  - docker build -t akshitsehgal297/multi-nginx ./nginx
  - docker build -t akshitsehgal297/multi-server ./server
  - docker build -t akshitsehgal297/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push akshitsehgal297/multi-client
  - docker push akshitsehgal297/multi-nginx
  - docker push akshitsehgal297/multi-server
  - docker push akshitsehgal297/multi-worker
